sudo: required

# setting the language to bash speeds up builds compared to the default since there is no ruby installation
language: bash

cache:
  ccache: true
  directories:
    $HOME/.ci/boost

services:
  - docker

install:
  - scripts/docker-hub-login
  - scripts/fetch-buildpack
  - buildpack/scripts/build-image

script:
  - buildpack/scripts/run-tests-in-container
  - buildpack/scripts/push-image

  # - 'if [ ! -z "$DOCKER_HUB_EMAIL" ]; then docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD; fi'
  # - wget https://api.github.com/repos/spark/firmware-buildpack-builder/tarball/feature/go_faster_stripes -O - | tar -xz -C ../ --strip-components 1
  # - ../scripts/build-image

#script:
  # - ../scripts/run-tests-in-container
  # - 'if [ "${UNIT_TEST}" = "y" ]; then ./ci/unit_tests.sh; else cd $DIR && make -s clean all DEBUG_BUILD=$DEBUG_BUILD PLATFORM=$PLATFORM COMPILE_LTO=$COMPILE_LTO TEST=$TEST SPARK_CLOUD=$SPARK_CLOUD APP=$APP; fi'
  # TODO - ./ci/integration_tests.sh
  # TODO  - ./ci/test_memory_available_with_real_core.sh

#after_success: ./ci/update-gh-pages.sh

git:
  depth: 1

env:
  matrix:
  # Travis doesn't like to spin up more than 5 concurrent jobs at a time
    - BUILD_PLATFORM="photon p1 unit-test"
    - BUILD_PLATFORM="electron core gcc"
    - BUILD_PLATFORM="xenon asom newhal"
    - BUILD_PLATFORM="argon bsom"
    - BUILD_PLATFORM="boron xsom"

  # matrix:
  #   - BUILD_PLATFORM=unit-test gcc
  #   - BUILD_PLATFORM=photon p1
  #   - BUILD_PLATFORM=core newhal
  #   - BUILD_PLATFORM=electron xenon

  # matrix:
  # - UNIT_TEST=y
  # - DIR=main    TEST=wiring/api        PLATFORM=photon COMPILE_LTO=n
  # - DIR=main    TEST=wiring/api        PLATFORM=core   COMPILE_LTO=n SPARK_CLOUD=n
  # - DIR=main    TEST=wiring/api        PLATFORM=P1     COMPILE_LTO=n
  # - DIR=main    TEST=wiring/no_fixture PLATFORM=photon COMPILE_LTO=n
  # - DIR=main    TEST=wiring/no_fixture PLATFORM=P1     COMPILE_LTO=n

  # # expansion of matrix
  # # dir=MAIN (monolithic)
  # # DEBUG_BUILD=y
  # # PLATFORM=core SPARK_CLOUD=y
  # - DIR=main    DEBUG_BUILD=y PLATFORM=core     SPARK_CLOUD=y APP=       COMPILE_LTO=y
  # - DIR=main    DEBUG_BUILD=y PLATFORM=core     SPARK_CLOUD=y APP=tinker COMPILE_LTO=y
  # - DIR=main    DEBUG_BUILD=y PLATFORM=core     SPARK_CLOUD=y APP=blank  COMPILE_LTO=y
  # # SPARK_CLOUD=n
  # - DIR=main    DEBUG_BUILD=y PLATFORM=core     SPARK_CLOUD=n APP=       COMPILE_LTO=y

  # # PLATFORM=photon SPARK_CLOUD=y
  # - DIR=main    DEBUG_BUILD=y PLATFORM=photon   SPARK_CLOUD=y APP=       COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=y PLATFORM=photon   SPARK_CLOUD=y APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=y PLATFORM=photon   SPARK_CLOUD=y APP=blank  COMPILE_LTO=n

  # # PLATFORM=P1 SPARK_CLOUD=y
  # - DIR=main    DEBUG_BUILD=y PLATFORM=P1       SPARK_CLOUD=y APP=       COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=y PLATFORM=P1       SPARK_CLOUD=y APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=y PLATFORM=P1       SPARK_CLOUD=y APP=blank  COMPILE_LTO=n

  # # PLATFORM=electron SPARK_CLOUD=y
  # - DIR=main    DEBUG_BUILD=y PLATFORM=electron SPARK_CLOUD=y APP=       COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=y PLATFORM=electron SPARK_CLOUD=y APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=y PLATFORM=electron SPARK_CLOUD=y APP=blank  COMPILE_LTO=n

  # # DEBUG_BUILD=n
  # # PLATFORM=core SPARK_CLOUD=y
  # - DIR=main    DEBUG_BUILD=n PLATFORM=core     SPARK_CLOUD=y APP=       COMPILE_LTO=y
  # - DIR=main    DEBUG_BUILD=n PLATFORM=core     SPARK_CLOUD=y APP=tinker COMPILE_LTO=y
  # - DIR=main    DEBUG_BUILD=n PLATFORM=core     SPARK_CLOUD=y APP=blank  COMPILE_LTO=y
  # # SPARK_CLOUD=n
  # - DIR=main    DEBUG_BUILD=n PLATFORM=core     SPARK_CLOUD=n APP=       COMPILE_LTO=y

  # # PLATFORM=photon SPARK_CLOUD=y
  # - DIR=main    DEBUG_BUILD=n PLATFORM=photon   SPARK_CLOUD=y APP=       COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=n PLATFORM=photon   SPARK_CLOUD=y APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=n PLATFORM=photon   SPARK_CLOUD=y APP=blank  COMPILE_LTO=n

  # # PLATFORM=P1 SPARK_CLOUD=y
  # - DIR=main    DEBUG_BUILD=n PLATFORM=P1       SPARK_CLOUD=y APP=       COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=n PLATFORM=P1       SPARK_CLOUD=y APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=n PLATFORM=P1       SPARK_CLOUD=y APP=blank  COMPILE_LTO=n

  # # PLATFORM=electron SPARK_CLOUD=y
  # - DIR=main    DEBUG_BUILD=n PLATFORM=electron SPARK_CLOUD=y APP=       COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=n PLATFORM=electron SPARK_CLOUD=y APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=n PLATFORM=electron SPARK_CLOUD=y APP=blank  COMPILE_LTO=n


  # # DIR=modules (modular)
  # # DEBUG_BUILD=y
  # - DIR=modules DEBUG_BUILD=y PLATFORM=photon   COMPILE_LTO=n
  # - DIR=modules DEBUG_BUILD=y PLATFORM=P1       COMPILE_LTO=n
  # # DEBUG_BUILD=n
  # - DIR=modules DEBUG_BUILD=n PLATFORM=photon   COMPILE_LTO=n
  # - DIR=modules DEBUG_BUILD=n PLATFORM=P1       COMPILE_LTO=n

  # # Photon minimal build
  # - DIR=modules PLATFORM=photon COMPILE_LTO=n MINIMAL=y
  global:
  - DOCKER_IMAGE_NAME=particle/buildpack-particle-firmware
  - secure: UM1+Ps1t21JfJaTFhuqkaY/U21j1Gfja6oSJTALcU0Y7zmo7TNyYMJwP+tbRfss7RBilWwUA8osr3sr6NXPREChojKpRQaRt52iD6wDfcxhsxGrpOU79cYO7FK1aQhCmhDGcnXahtxzbOGwS74jjTFW9U6TSveWa+EV1OgagLMc=
  - secure: aJ+EUGgXIp8t0s/f3EEyiUjYXnzAlYW9+jukG240A2Wb/XnGp9Av/JE+wBnBeMv7eF+hxkODo99gDXPumV6uYQevIBtqiHWtAu7kyvCxUWXhSmag+Q89pCJO8QpUrcxra9UZ6i+zhFEfskBctBjlT9nMKoUsGSg4jMg6Kx71QsA=
  - secure: Iq58mKqq5Nz4B6OEZu1nmnquhvlQncxT4T3f1x+M/0I6VW5xirMWFlpeke8QyyPOZlwNLDnB5QVjsR2UQspNIhMT4rCfDeCCr9AeinoMDmqPbzpmLLmtaUpz0uTZyJVx7+IRe9QtljPfbzlAxybmrx1HdCCw++F/+qhgFoGLi9o=
  - secure: O8Zu2sWO63svmSTdOk+7Z7N2oUcg3N07WckMoy1m7AYmRZydX5hdVXlbagA06FCtpu1Kvvwc7QYB+1wpoxZYZnxt2mVetVsAcSpOz3c03LodM+yKaHm9luqLfQobuC7oyNdumpqMLsWiELM9rxEpIazYDYM2QI+lh7fTUTHnQ3s=
  - secure: A83drTFobkGvgrPNwGwNS3ZSHX35iNELjH6W9h07pw/n1YSssBHxtLF8aVAEwfIF1VyUoHvQ4HYLNd+9RMyo162xxiWne+/4/gSFyUJNi11w3YX5bwodKPl7OwEO/YnJgHYk8YAAfdnZT4470Fpt6ytcOhEhMsB/IFeepMUiZZA=

notifications:
    slack: s:uyDgDeY2Sric20NcE50P11QS
