sudo: required

# setting the language to bash speeds up builds compared to the default since there is no ruby installation
language: bash

cache:
  ccache: true
  directories:
    $HOME/.ci/boost

services:
  - docker

install:
  - scripts/docker-hub-login
  - scripts/fetch-buildpack
  - buildpack/scripts/build-image

script:
  - buildpack/scripts/run-tests-in-container
  - 'if [ -f /home/travis/build/.build/coverage.json ]; then python ci/report/report.py /home/travis/build/.build/coverage.json; rm -f /home/travis/build/.build/coverage.json; fi'
  - buildpack/scripts/push-image

  # - 'if [ ! -z "$DOCKER_HUB_EMAIL" ]; then docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD; fi'
  # - wget https://api.github.com/repos/spark/firmware-buildpack-builder/tarball/feature/go_faster_stripes -O - | tar -xz -C ../ --strip-components 1
  # - ../scripts/build-image

#script:
  # - ../scripts/run-tests-in-container
  # - 'if [ "${UNIT_TEST}" = "y" ]; then ./ci/unit_tests.sh; else cd $DIR && make -s clean all DEBUG_BUILD=$DEBUG_BUILD PLATFORM=$PLATFORM COMPILE_LTO=$COMPILE_LTO TEST=$TEST APP=$APP; fi'
  # TODO - ./ci/integration_tests.sh

#after_success: ./ci/update-gh-pages.sh

git:
  depth: 1

env:
  matrix:
  # Travis doesn't like to spin up more than 5 concurrent jobs at a time
    - BUILD_PLATFORM="photon p1"
    - BUILD_PLATFORM="gcc unit-test newhal tracker"
    - BUILD_PLATFORM="electron boron"
    - BUILD_PLATFORM="xenon argon"
    - BUILD_PLATFORM="bsom b5som"

  # matrix:
  #   - BUILD_PLATFORM=unit-test gcc
  #   - BUILD_PLATFORM=photon p1
  #   - BUILD_PLATFORM=newhal
  #   - BUILD_PLATFORM=electron xenon

  # matrix:
  # - UNIT_TEST=y
  # - DIR=main    TEST=wiring/api        PLATFORM=photon COMPILE_LTO=n
  # - DIR=main    TEST=wiring/api        PLATFORM=P1     COMPILE_LTO=n
  # - DIR=main    TEST=wiring/no_fixture PLATFORM=photon COMPILE_LTO=n
  # - DIR=main    TEST=wiring/no_fixture PLATFORM=P1     COMPILE_LTO=n

  # # expansion of matrix
  # # dir=MAIN (monolithic)

  # # PLATFORM=photon
  # - DIR=main    DEBUG_BUILD=y PLATFORM=photon APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=y PLATFORM=photon APP=blank  COMPILE_LTO=n

  # # PLATFORM=P1
  # - DIR=main    DEBUG_BUILD=y PLATFORM=P1 APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=y PLATFORM=P1 APP=blank  COMPILE_LTO=n

  # # PLATFORM=electron
  # - DIR=main    DEBUG_BUILD=y PLATFORM=electron APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=y PLATFORM=electron APP=blank  COMPILE_LTO=n

  # # PLATFORM=photon
  # - DIR=main    DEBUG_BUILD=n PLATFORM=photon APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=n PLATFORM=photon APP=blank  COMPILE_LTO=n

  # # PLATFORM=P1
  # - DIR=main    DEBUG_BUILD=n PLATFORM=P1 APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=n PLATFORM=P1 APP=blank  COMPILE_LTO=n

  # # PLATFORM=electron
  # - DIR=main    DEBUG_BUILD=n PLATFORM=electron APP=tinker COMPILE_LTO=n
  # - DIR=main    DEBUG_BUILD=n PLATFORM=electron APP=blank  COMPILE_LTO=n


  # # DIR=modules (modular)
  # # DEBUG_BUILD=y
  # - DIR=modules DEBUG_BUILD=y PLATFORM=photon   COMPILE_LTO=n
  # - DIR=modules DEBUG_BUILD=y PLATFORM=P1       COMPILE_LTO=n
  # # DEBUG_BUILD=n
  # - DIR=modules DEBUG_BUILD=n PLATFORM=photon   COMPILE_LTO=n
  # - DIR=modules DEBUG_BUILD=n PLATFORM=P1       COMPILE_LTO=n

  # # Photon minimal build
  # - DIR=modules PLATFORM=photon COMPILE_LTO=n MINIMAL=y
  global:
  - DOCKER_IMAGE_NAME=particle/buildpack-particle-firmware
  - secure: UM1+Ps1t21JfJaTFhuqkaY/U21j1Gfja6oSJTALcU0Y7zmo7TNyYMJwP+tbRfss7RBilWwUA8osr3sr6NXPREChojKpRQaRt52iD6wDfcxhsxGrpOU79cYO7FK1aQhCmhDGcnXahtxzbOGwS74jjTFW9U6TSveWa+EV1OgagLMc=
  - secure: aJ+EUGgXIp8t0s/f3EEyiUjYXnzAlYW9+jukG240A2Wb/XnGp9Av/JE+wBnBeMv7eF+hxkODo99gDXPumV6uYQevIBtqiHWtAu7kyvCxUWXhSmag+Q89pCJO8QpUrcxra9UZ6i+zhFEfskBctBjlT9nMKoUsGSg4jMg6Kx71QsA=
  - secure: Iq58mKqq5Nz4B6OEZu1nmnquhvlQncxT4T3f1x+M/0I6VW5xirMWFlpeke8QyyPOZlwNLDnB5QVjsR2UQspNIhMT4rCfDeCCr9AeinoMDmqPbzpmLLmtaUpz0uTZyJVx7+IRe9QtljPfbzlAxybmrx1HdCCw++F/+qhgFoGLi9o=
  - secure: O8Zu2sWO63svmSTdOk+7Z7N2oUcg3N07WckMoy1m7AYmRZydX5hdVXlbagA06FCtpu1Kvvwc7QYB+1wpoxZYZnxt2mVetVsAcSpOz3c03LodM+yKaHm9luqLfQobuC7oyNdumpqMLsWiELM9rxEpIazYDYM2QI+lh7fTUTHnQ3s=
  - secure: A83drTFobkGvgrPNwGwNS3ZSHX35iNELjH6W9h07pw/n1YSssBHxtLF8aVAEwfIF1VyUoHvQ4HYLNd+9RMyo162xxiWne+/4/gSFyUJNi11w3YX5bwodKPl7OwEO/YnJgHYk8YAAfdnZT4470Fpt6ytcOhEhMsB/IFeepMUiZZA=
notifications:
  slack:
    rooms:
      secure: Q+HuLmEeqSkRfiMYvqQpT7R6pfVghZ1OIXSm2hTAu3HVrMGBj6Jyp23k8EBnwjUnKxP/XZ88ARd3rOZF/vZF7wXixBhQtTdThUMUdKXAhvUkRHU0vmF7t+atsucwu1yp21jjWL7csnHmuH4qAoNdgLnoJYFImgRFoxB3weqVnEs=
